version: "3.3"

services:
  todo-server:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    working_dir: /app
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
  redis:
    image: redis # port 6379
    restart: always